In [25]:
import scipy.io as sio
import numpy as np
import imageio as iio
from scipy.special import softmax
import json
from PIL import Image

In [2]:
annoatation_path = "./data/coco_stuff10k/annotations/"
output_path = "./pro_data/coco_stuff10k/out/test/"

In [32]:
file_name = "COCO_train2014_000000000825"
image_path = "./data/coco_stuff10k/images/"
image = np.asarray(Image.open(image_path + file_name + ".jpg"), dtype=np.float32)

In [33]:
image.shape

(480, 640, 3)

In [19]:
def np_read(file):
    with open(file, "rb") as outfile:
        data = np.load(outfile)
    return data
def np_write(data, file):
    with open(file, "wb") as outfile:
        np.save(outfile, data)
        
def write_one_results(path, json_data):
    with open(path, "w") as outfile:
        json.dump(json_data, outfile)

def read_one_results(path):
    with open(path, "r") as outfile:
        data = json.load(outfile)
    return data

In [4]:
file_name = "COCO_train2014_000000000825"
labels = sio.loadmat(annoatation_path + file_name + ".mat")['S']
outputs = np_read(output_path + file_name + ".npy")

In [15]:
labels

array([[167, 167, 167, ..., 167, 167, 167],
       [167, 167, 167, ..., 167, 167, 167],
       [167, 167, 167, ..., 167, 167, 167],
       ...,
       [167, 167, 167, ..., 167, 167, 167],
       [167, 167, 167, ..., 167, 167, 167],
       [167, 167, 167, ..., 167, 167, 167]], dtype=uint8)

In [16]:
labels.min(), labels.max()

(17, 167)

In [13]:
temp_outputs = softmax(outputs, axis=0)
results = temp_outputs.argmax(axis=0)

In [30]:
results

array([[59, 59, 59, ..., 59, 59, 59],
       [59, 59, 59, ..., 59, 59, 59],
       [59, 59, 59, ..., 59, 59, 59],
       ...,
       [59, 59, 59, ..., 59, 59, 59],
       [59, 59, 59, ..., 59, 59, 59],
       [59, 59, 59, ..., 59, 59, 59]])

In [22]:
json_data = read_one_results("./data/coco_stuff10k/cocostuff-10k-v1.1.json")

In [26]:
image = np.asarray(Image.open(annoatation_path + "test2014/" + file_name + "_labelTrainIds.png"), dtype=np.float32)

In [29]:
image

array([[156., 156., 156., ..., 156., 156., 156.],
       [156., 156., 156., ..., 156., 156., 156.],
       [156., 156., 156., ..., 156., 156., 156.],
       ...,
       [156., 156., 156., ..., 156., 156., 156.],
       [156., 156., 156., ..., 156., 156., 156.],
       [156., 156., 156., ..., 156., 156., 156.]], dtype=float32)